/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import clases.cls_clientes;
import clases.detalle_orden;
import clases.modeloProductos;
import clases.orden;
import clases.productos;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSi
 */
public class frm_empleados extends javax.swing.JFrame {

    public static cls_clientes c = new cls_clientes();
    public static productos p = new productos();
    public static detalle_orden deto = new detalle_orden();
    public static orden o = new orden();
    public static DefaultTableModel modelo;
    int item;
    private String dato;
    public static DefaultTableModel modelop;
    public static DefaultTableModel modelopro;
    public static DefaultTableModel modelord;
    Double totalPagar = 0.00;

    /**
     * Creates new form frm_empleados
     */
    public frm_empleados() {
        initComponents();
        txt_id_cliente.setVisible(false);
        Icon logo1 = new ImageIcon(new ImageIcon(getClass().getResource("/imagenes/banner4.jpg")).getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), 0));
        jLabel1.setIcon(logo1);

        Icon logo2 = new ImageIcon(new ImageIcon(getClass().getResource("/imagenes/logo1.png")).getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), 0));
        jLabel2.setIcon(logo2);
        txt_idventa.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_tabpro = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbl_ide = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbx_pizza = new javax.swing.JComboBox<productos>();
        jLabel12 = new javax.swing.JLabel();
        txt_preciop = new javax.swing.JTextField();
        btn_seleccionarp = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_cantp = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_pro = new javax.swing.JTable();
        btn_agregarp = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cbx_bebida = new javax.swing.JComboBox<productos>();
        btn_seleccionarb = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txt_preciob = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_cantb = new javax.swing.JTextField();
        btn_agregarb = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        btn_elitabla = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txt_idcliv = new javax.swing.JTextField();
        txt_cedcliv = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_nombrecliv = new javax.swing.JTextField();
        txt_apecliv = new javax.swing.JTextField();
        btn_regventa = new javax.swing.JButton();
        txt_telcliv = new javax.swing.JTextField();
        txt_dircliv = new javax.swing.JTextField();
        txt_correocliv = new javax.swing.JTextField();
        btn_accept = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_cedulacli = new javax.swing.JTextField();
        txt_nombrecli = new javax.swing.JTextField();
        txt_apecli = new javax.swing.JTextField();
        txt_telcli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_dircli = new javax.swing.JTextField();
        txt_correocli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_cliente = new javax.swing.JTable();
        btn_nuevocli = new javax.swing.JButton();
        btn_guardarcli = new javax.swing.JButton();
        btn_actualizarcli = new javax.swing.JButton();
        btn_eliminarcli = new javax.swing.JButton();
        txt_id_cliente = new javax.swing.JTextField();
        btn_cancelarcli = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_p = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_ord = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_idventa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Order Pizza", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Módulo de caja");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 400, 70));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Order Pizza", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/order.png"))); // NOI18N
        jButton1.setText("Nueva Orden");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Order Pizza", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inconocliente.png"))); // NOI18N
        jButton2.setText("Clientes");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_tabpro.setFont(new java.awt.Font("Order Pizza", 0, 12)); // NOI18N
        btn_tabpro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoorden.png"))); // NOI18N
        btn_tabpro.setText("Productos");
        btn_tabpro.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_tabpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tabproActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Order Pizza", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden1.png"))); // NOI18N
        jButton4.setText("Ordenes");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lbl_ide.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_tabpro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lbl_ide, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ide)
                .addGap(24, 24, 24)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_tabpro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banner4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 890, 130));

        jLabel10.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel10.setText("Pizza:");

        cbx_pizza.setModel(new javax.swing.DefaultComboBoxModel<>(new productos[] {}));

        jLabel12.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel12.setText("Precio:");

        txt_preciop.setEditable(false);

        btn_seleccionarp.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_seleccionarp.setText("Seleccionar");
        btn_seleccionarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionarpActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel13.setText("Cantidad:");

        tabla_pro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Producto", "Tamaño", "Cantidad", "Precio"
            }
        ));
        jScrollPane3.setViewportView(tabla_pro);

        btn_agregarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check.png"))); // NOI18N
        btn_agregarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarpActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel14.setText("Bebida:");

        btn_seleccionarb.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_seleccionarb.setText("Seleccionar");
        btn_seleccionarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionarbActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel15.setText("Precio:");

        txt_preciob.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel16.setText("Cantidad:");

        btn_agregarb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check.png"))); // NOI18N
        btn_agregarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarbActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel17.setText("Total:");

        lbl_total.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btn_elitabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_elitabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elitablaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel18.setText("CI o RUC:");

        txt_idcliv.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel19.setText("Nombre:");

        btn_regventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprim.png"))); // NOI18N
        btn_regventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regventaActionPerformed(evt);
            }
        });

        txt_telcliv.setEditable(false);
        txt_telcliv.setText("jTextField1");

        txt_dircliv.setEditable(false);
        txt_dircliv.setText("jTextField5");

        txt_correocliv.setEditable(false);
        txt_correocliv.setText("jTextField6");

        btn_accept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btn_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_elitabla)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_idcliv, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_telcliv, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_dircliv, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_correocliv, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(394, 394, 394)
                                .addComponent(jLabel17)
                                .addGap(26, 26, 26)
                                .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txt_cedcliv, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_accept)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nombrecliv, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_apecliv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_regventa)))
                        .addGap(221, 221, 221))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_preciop, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cantp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbx_pizza, 0, 235, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agregarp)
                    .addComponent(btn_seleccionarp))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_seleccionarb, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_preciob, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cantb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_agregarb)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbx_pizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(cbx_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_seleccionarb)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_seleccionarp)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_preciop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txt_cantp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btn_agregarp))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_preciob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txt_cantb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_agregarb)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_elitabla)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_idcliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_telcliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_dircliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_correocliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(txt_cedcliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19)
                                .addComponent(txt_nombrecliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_apecliv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_regventa)))
                    .addComponent(btn_accept))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jLabel4.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel4.setText("Cedula o RUC:");

        jLabel5.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel6.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel6.setText("Apellido:");

        jLabel7.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel7.setText("Telefono:");

        jLabel8.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel8.setText("Direccion:");

        jLabel9.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel9.setText("Correo:");

        tabla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CI/RUC", "Nombre", "Apellido", "Teléfono", "Dirección", "Correo"
            }
        ));
        tabla_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_cliente);
        if (tabla_cliente.getColumnModel().getColumnCount() > 0) {
            tabla_cliente.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabla_cliente.getColumnModel().getColumn(1).setPreferredWidth(20);
            tabla_cliente.getColumnModel().getColumn(2).setPreferredWidth(20);
            tabla_cliente.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        btn_nuevocli.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_nuevocli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btn_nuevocli.setText("Nuevo");
        btn_nuevocli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevocliActionPerformed(evt);
            }
        });

        btn_guardarcli.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_guardarcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardarcli.setText("Guardar");
        btn_guardarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarcliActionPerformed(evt);
            }
        });

        btn_actualizarcli.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_actualizarcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizarcli.setText("Actualizar");
        btn_actualizarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarcliActionPerformed(evt);
            }
        });

        btn_eliminarcli.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_eliminarcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_eliminarcli.setText("Eliminar");
        btn_eliminarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarcliActionPerformed(evt);
            }
        });

        btn_cancelarcli.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_cancelarcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btn_cancelarcli.setText("Cancelar");
        btn_cancelarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarcliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(btn_nuevocli)
                            .addGap(18, 18, 18)
                            .addComponent(btn_guardarcli))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_cedulacli, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_nombrecli)
                                        .addComponent(txt_apecli)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_telcli)
                                        .addComponent(txt_dircli)))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_correocli)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_actualizarcli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminarcli, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btn_cancelarcli, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_cedulacli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_nombrecli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_apecli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_telcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_dircli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_correocli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_nuevocli)
                            .addComponent(btn_guardarcli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_actualizarcli, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_eliminarcli, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelarcli))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_p.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Producto", "Producto", "Tamaño", "Precio"
            }
        ));
        tabla_p.setEnabled(false);
        jScrollPane2.setViewportView(tabla_p);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 600, 320));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondop.jpg"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 410));

        jTabbedPane1.addTab("tab3", jPanel4);

        tabla_ord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "# ORDEN", "Nombre Cliente", "Apellido Cliente", "Cod. Cajero", "Total"
            }
        ));
        tabla_ord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_ordMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabla_ord);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impreg.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel20.setText("Seleccione la factura que desea imprimir");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-derecha-abajo-2-32.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(txt_idventa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(txt_idventa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))))
        );

        jTabbedPane1.addTab("tab4", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 880, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        jTabbedPane1.setSelectedIndex(1);
        tablaClientes();
        bcajacli();
        bbotoncli();
        btn_nuevocli.setEnabled(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabla_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_clienteMouseClicked

        String cedula = tabla_cliente.getValueAt(tabla_cliente.getSelectedRow(), 0).toString();
        String[] dato = new String[7];
        dato = c.consultarCed(cedula);

        if (dato != null) {
            bbotoncli();
            btn_eliminarcli.setEnabled(true);
            btn_actualizarcli.setEnabled(true);
            btn_cancelarcli.setEnabled(true);
            acajacli();
            txt_id_cliente.setText(dato[0]);
            txt_cedulacli.setText(dato[1]);
            txt_nombrecli.setText(dato[2]);
            txt_apecli.setText(dato[3]);
            txt_telcli.setText(dato[4]);
            txt_dircli.setText(dato[5]);
            txt_correocli.setText(dato[6]);
        }

    }//GEN-LAST:event_tabla_clienteMouseClicked

    private void btn_nuevocliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevocliActionPerformed

        acajacli();
        btn_guardarcli.setEnabled(true);
        btn_cancelarcli.setEnabled(true);

    }//GEN-LAST:event_btn_nuevocliActionPerformed

    private void btn_guardarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarcliActionPerformed

        c.setCedula(txt_cedulacli.getText());
        c.setNombre(txt_nombrecli.getText());
        c.setApellido(txt_apecli.getText());
        c.setTelefono(txt_telcli.getText());
        c.setDireccion(txt_dircli.getText());
        c.setCorreo(txt_correocli.getText());

        if (c.insertar() == true) {
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente");
            bcajacli();
            lcajacli();
            bbotoncli();
            btn_nuevocli.setEnabled(true);
            tablaClientes();
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar");
        }

    }//GEN-LAST:event_btn_guardarcliActionPerformed

    private void btn_actualizarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarcliActionPerformed

        c.setCedula(txt_cedulacli.getText());
        c.setNombre(txt_nombrecli.getText());
        c.setApellido(txt_apecli.getText());
        c.setTelefono(txt_telcli.getText());
        c.setDireccion(txt_dircli.getText());
        c.setCorreo(txt_correocli.getText());
        c.setId_cliente(Integer.parseInt(txt_id_cliente.getText()));

        if (c.actualizar() == true) {

            JOptionPane.showMessageDialog(null, "Datos actualizados");
            bcajacli();
            lcajacli();
            bbotoncli();
            btn_nuevocli.setEnabled(true);
            tablaClientes();
        } else {
            JOptionPane.showMessageDialog(null, "Error al actualizar");
        }

    }//GEN-LAST:event_btn_actualizarcliActionPerformed

    private void btn_eliminarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarcliActionPerformed

        int respuesta = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el registro?");
        if (respuesta == 0) {
            c.setId_cliente(Integer.parseInt(txt_id_cliente.getText()));
            if (c.eliminar()) {
                JOptionPane.showMessageDialog(null, "Registro eliminado");
                bcajacli();
                lcajacli();
                bbotoncli();
                btn_nuevocli.setEnabled(true);
                tablaClientes();
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar");
            }
        }
    }//GEN-LAST:event_btn_eliminarcliActionPerformed

    private void btn_cancelarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarcliActionPerformed

        bcajacli();
        lcajacli();
        bbotoncli();
        btn_nuevocli.setEnabled(true);

    }//GEN-LAST:event_btn_cancelarcliActionPerformed

    private void btn_tabproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tabproActionPerformed

        jTabbedPane1.setSelectedIndex(2);
        try {
            tablaProductos();
        } catch (SQLException ex) {
            Logger.getLogger(frm_empleados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_tabproActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        jTabbedPane1.setSelectedIndex(0);
        llenarPizza();
        try {
            llenarBebida();
        } catch (SQLException ex) {
            Logger.getLogger(frm_empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        llenarPizza();
        try {
            llenarBebida();
        } catch (SQLException ex) {
            Logger.getLogger(frm_empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txt_idcliv.setVisible(false);
        txt_telcliv.setVisible(false);
        txt_dircliv.setVisible(false);
        txt_correocliv.setVisible(false);
        

    }//GEN-LAST:event_formComponentShown

    private void btn_seleccionarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionarpActionPerformed

        double precio = cbx_pizza.getItemAt(cbx_pizza.getSelectedIndex()).getPrecio();
        txt_preciop.setText(String.valueOf(precio));
        

    }//GEN-LAST:event_btn_seleccionarpActionPerformed

    private void btn_agregarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarpActionPerformed
        
        int id_producto = cbx_pizza.getItemAt(cbx_pizza.getSelectedIndex()).getId_producto();
        String producto = cbx_pizza.getItemAt(cbx_pizza.getSelectedIndex()).getProducto();
        String tamano = cbx_pizza.getItemAt(cbx_pizza.getSelectedIndex()).getTamano();
        int cant = Integer.parseInt(txt_cantp.getText());
        double precio = Double.parseDouble(txt_preciop.getText());
        double preciofp = precio * cant;
        
        if(cant != 0){
            item=item+1;
            modelop = (DefaultTableModel) tabla_pro.getModel();
            ArrayList lista = new ArrayList();
            lista.add(item);
            lista.add(id_producto);
            lista.add(producto);
            lista.add(tamano);
            lista.add(cant);
            lista.add(preciofp);
            
            Object [] o = new Object[5];
            o[0]=lista.get(1);
            o[1]=lista.get(2);
            o[2]=lista.get(3);
            o[3]=lista.get(4);
            o[4]=lista.get(5);
            
            modelop.addRow(o);
            
            totalPagar();
            tabla_pro.setModel(modelop);
            txt_preciop.setText("");
            txt_cantp.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese cantidad");
        }
    }//GEN-LAST:event_btn_agregarpActionPerformed

    private void btn_seleccionarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionarbActionPerformed
        
        double precio = cbx_bebida.getItemAt(cbx_bebida.getSelectedIndex()).getPrecio();
        txt_preciob.setText(String.valueOf(precio));
    
    }//GEN-LAST:event_btn_seleccionarbActionPerformed

    private void btn_agregarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarbActionPerformed
        
        int id_producto = cbx_bebida.getItemAt(cbx_bebida.getSelectedIndex()).getId_producto();
        String producto = cbx_bebida.getItemAt(cbx_bebida.getSelectedIndex()).getProducto();
        String tamano = "";
        int cantb = Integer.parseInt(txt_cantb.getText());
        double precio = cbx_bebida.getItemAt(cbx_bebida.getSelectedIndex()).getPrecio();
        double preciofb = precio * cantb;
        
        if(cantb != 0){
            item=item+1;
            modelop = (DefaultTableModel) tabla_pro.getModel();
            ArrayList listab = new ArrayList();
            listab.add(item);
            listab.add(id_producto);
            listab.add(producto);
            listab.add(tamano);
            listab.add(cantb);
            listab.add(preciofb);
            
            Object[] o = new Object[5];
            o[0]=listab.get(1);
            o[1]=listab.get(2);
            o[2]=listab.get(3);
            o[3]=listab.get(4);
            o[4]=listab.get(5);
            
            modelop.addRow(o);
            
            totalPagar();
            tabla_pro.setModel(modelop);
            txt_preciob.setText("");
            txt_cantb.setText("");
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese cantidad");
        }
        
    }//GEN-LAST:event_btn_agregarbActionPerformed

    private void btn_elitablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elitablaActionPerformed
        
        modelop = (DefaultTableModel) tabla_pro.getModel();
        modelop.removeRow(tabla_pro.getSelectedRow());
        totalPagar();
    }//GEN-LAST:event_btn_elitablaActionPerformed

    private void btn_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acceptActionPerformed
        
        if(!"".equals(txt_cedcliv.getText())){
            String cedcli = txt_cedcliv.getText();
            try {
                if(c.buscarCliente(cedcli)){
                    txt_nombrecliv.setText(c.getNombre());
                    txt_apecliv.setText(c.getApellido());
                    txt_idcliv.setText(String.valueOf(c.getId_cliente()));
                    txt_telcliv.setText(c.getTelefono());
                    txt_dircliv.setText(c.getDireccion());
                    txt_correocliv.setText(c.getCorreo());
                }else{
                    JOptionPane.showMessageDialog(null, "El cliente no existe");
                }
            } catch (SQLException ex) {
                Logger.getLogger(frm_empleados.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese cédula de cliente");
        }
        
    }//GEN-LAST:event_btn_acceptActionPerformed

    private void btn_regventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regventaActionPerformed
        
        o.setId_cliente(Integer.parseInt(txt_idcliv.getText()));
        o.setId_empleado(Integer.parseInt(lbl_ide.getText()));
        o.setTotal(Double.parseDouble(lbl_total.getText()));
        
        if(o.resgistrarOrden()){
            registrarD();
            try {
                pdf();
            } catch (DocumentException ex) {
                Logger.getLogger(frm_empleados.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(frm_empleados.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Orden registrada correctamente");
            lcajaor();
            limpiarOrden(modelop);
            totalPagar();
        }else{
            JOptionPane.showMessageDialog(null, "Error al registrar la orden");
        }
        
        
    }//GEN-LAST:event_btn_regventaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        jTabbedPane1.setSelectedIndex(3);
        tablaOrd();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabla_ordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_ordMouseClicked
        
        int fila = tabla_ord.rowAtPoint(evt.getPoint());
        txt_idventa.setText(tabla_ord.getValueAt(fila, 0).toString());
        
    }//GEN-LAST:event_tabla_ordMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int id = Integer.parseInt(txt_idventa.getText());
        File file = new File("src/pdf/factura"+id+".pdf");
        try {
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(frm_empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_empleados().setVisible(true);
            }
        });
    }

    public void tablaClientes() {

        String[] cabecera = {"Cedula", "Nombre", "Apellido", "Telefono", "Direccion", "Correo"};
        try {
            modelo = new DefaultTableModel(c.consultar(txt_cedulacli.getText()), cabecera);
        } catch (Exception e) {
            e.printStackTrace();
        }

        tabla_cliente.setModel(modelo);
    }
    
    public void tablaProductos() throws SQLException{
        
        String[] cabecera = {"Cod. Producto", "Producto", "Tamaño", "Precio"};
        modelopro = new DefaultTableModel(p.consultar(), cabecera);
        tabla_p.setModel(modelopro);
    }
    
    public void tablaOrd(){
        
        String[] cabecera = {"# ORDEN", "Nombre Cliente", "Apellido Cliente", "Cod. Cajero", "Total"};
        modelord = new DefaultTableModel(o.consultarOrden(), cabecera);
        tabla_ord.setModel(modelord);
    }

    public void bcajacli() {

        this.txt_cedulacli.setEnabled(false);
        this.txt_nombrecli.setEnabled(false);
        this.txt_apecli.setEnabled(false);
        this.txt_telcli.setEnabled(false);
        this.txt_dircli.setEnabled(false);
        this.txt_correocli.setEnabled(false);
        this.txt_id_cliente.setEnabled(false);
    }

    public void acajacli() {

        this.txt_cedulacli.setEnabled(true);
        this.txt_nombrecli.setEnabled(true);
        this.txt_apecli.setEnabled(true);
        this.txt_telcli.setEnabled(true);
        this.txt_dircli.setEnabled(true);
        this.txt_correocli.setEnabled(true);
        this.txt_id_cliente.setEnabled(true);
    }

    public void lcajacli() {

        this.txt_id_cliente.setText("");
        this.txt_cedulacli.setText("");
        this.txt_nombrecli.setText("");
        this.txt_apecli.setText("");
        this.txt_telcli.setText("");
        this.txt_dircli.setText("");
        this.txt_correocli.setText("");
    }

    public void bbotoncli() {

        this.btn_nuevocli.setEnabled(false);
        this.btn_guardarcli.setEnabled(false);
        this.btn_actualizarcli.setEnabled(false);
        this.btn_eliminarcli.setEnabled(false);
        this.btn_cancelarcli.setEnabled(false);
    }

    private void llenarPizza() {

        modeloProductos mp = new modeloProductos();
        ArrayList<productos> listado = mp.combo_p();
        cbx_pizza.removeAllItems();

        for (int i = 0; i < listado.size(); i++) {
            cbx_pizza.addItem(new productos(listado.get(i).getId_producto(), listado.get(i).getProducto(), listado.get(i).getTamano(), listado.get(i).getPrecio()));
        }

    }

    private void llenarBebida() throws SQLException {

        modeloProductos mb = new modeloProductos();
        ArrayList<productos> listadob = mb.combo_b();
        cbx_bebida.removeAllItems();

        for (int i = 0; i < listadob.size(); i++) {
            cbx_bebida.addItem(new productos(listadob.get(i).getId_producto(), listadob.get(i).getProducto(), listadob.get(i).getTamano(), listadob.get(i).getPrecio()));
        }

    }
    
    private void totalPagar(){
        
        totalPagar=0.0;
        
        for(int i=0; i<tabla_pro.getRowCount();i++){
            
            String sub = String.valueOf(tabla_pro.getModel().getValueAt(i, 4));
            double precio_i = Double.parseDouble(sub);
            totalPagar += precio_i;
            
        }
        
        lbl_total.setText(String.valueOf(totalPagar));  
    }
    
    private void lcajaor(){
        
        txt_cedcliv.setText("");
        txt_idcliv.setText("");
        txt_nombrecliv.setText("");
        txt_apecliv.setText("");
        txt_telcliv.setText("");
        txt_dircliv.setText("");
        txt_correocliv.setText("");
    }
    
    public void limpiarOrden(DefaultTableModel modelop){
        
        while(modelop.getRowCount()>0){
            modelop.removeRow(0);
        }
        
    }
    
    private void registrarD(){
        
        for(int i =0; i<tabla_pro.getRowCount();i++){
            deto.setId_orden(o.id_orden());
            deto.setId_producto(Integer.parseInt(tabla_pro.getValueAt(i, 0).toString()));
            deto.setCantidad(Integer.parseInt(tabla_pro.getValueAt(i, 3).toString()));
            deto.setPrecio(Double.parseDouble(tabla_pro.getValueAt(i, 4).toString()));
            if(deto.registrarDetalle()){
            }
        }
        
    }
    
    public void pdf() throws FileNotFoundException, DocumentException, BadElementException, IOException{
    
     try{
         int id = o.id_orden();
        FileOutputStream archivo;
        File file = new File("src/pdf/factura"+id+".pdf");
        archivo = new FileOutputStream(file);
        Document doc = new Document();
        PdfWriter.getInstance(doc, archivo);
        doc.open();
        Image img;
        img= Image.getInstance("src/imagenes/logo1.png");
        
        Paragraph fecha = new Paragraph();
        Font negrita = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD, BaseColor.BLACK);
        fecha.add(Chunk.NEWLINE);
        Date date = new Date();
        fecha.add("Factura: "+id+"\n"+"Fecha: "+new SimpleDateFormat("dd-MM-yyyy").format(date)+"\n\n");
        
        PdfPTable encabezado = new PdfPTable(4);
        encabezado.setWidthPercentage(100);
        encabezado.getDefaultCell().setBorder(0);
        float[] columnae = new float[]{20f, 30f, 70, 40f};
        encabezado.setWidths(columnae);
        encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
        
        encabezado.addCell(img);
        String ruc = "1094657635";
        String nombre = "Pizza Express Inc.";
        String telefono = "0956783546";
        String direccion = "Cuenca, Ecuador";
        
        encabezado.addCell("");
        encabezado.addCell("RUC: "+ruc+ "\nNombre: "+nombre+" \nTeléfono: "+ telefono +"\nDirección: "+direccion);
        encabezado.addCell(fecha);
        doc.add(encabezado);
        
        Paragraph clientes = new Paragraph();
        clientes.add(Chunk.NEWLINE);
        clientes.add("Datos del cliente"+"\n\n");
        doc.add(clientes);
        
        PdfPTable tabclientes = new PdfPTable(5);
        tabclientes.setWidthPercentage(100);
        tabclientes.getDefaultCell().setBorder(0);
        float[] columnacli = new float[]{30f, 40f, 30, 40f, 40f};
        tabclientes.setWidths(columnacli);
        tabclientes.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell cli1 = new PdfPCell(new Phrase("CI/RUC:", negrita));
        PdfPCell cli2 = new PdfPCell(new Phrase("Nombre:", negrita));
        PdfPCell cli3 = new PdfPCell(new Phrase("Teléfono:", negrita));
        PdfPCell cli4 = new PdfPCell(new Phrase("Dirección:", negrita));
        PdfPCell cli5 = new PdfPCell(new Phrase("Correo:", negrita));
        cli1.setBorder(0);
        cli2.setBorder(0);
        cli3.setBorder(0);
        cli4.setBorder(0);
        cli5.setBorder(0);
        cli1.setBackgroundColor(BaseColor.RED);
        cli2.setBackgroundColor(BaseColor.RED);
        cli3.setBackgroundColor(BaseColor.RED);
        cli4.setBackgroundColor(BaseColor.RED);
        cli5.setBackgroundColor(BaseColor.RED);
        
        tabclientes.addCell(cli1);
        tabclientes.addCell(cli2);
        tabclientes.addCell(cli3);
        tabclientes.addCell(cli4);
        tabclientes.addCell(cli5);
        tabclientes.addCell(txt_cedcliv.getText());
        tabclientes.addCell(txt_nombrecliv.getText()+" "+txt_apecliv.getText());
        tabclientes.addCell(txt_telcliv.getText());
        tabclientes.addCell(txt_dircliv.getText());
        tabclientes.addCell(txt_correocliv.getText()+"\n");
        
        doc.add(tabclientes);
        
        Paragraph prods = new Paragraph();
        prods.add(Chunk.NEWLINE);
        prods.add("Detalle de productos"+"\n\n");
        doc.add(prods);
        
        PdfPTable tabproductos = new PdfPTable(4);
        tabproductos.setWidthPercentage(100);
        tabproductos.getDefaultCell().setBorder(0);
        float[] columnapro = new float[]{40f, 50f, 30, 40f};
        tabproductos.setWidths(columnapro);
        tabproductos.setHorizontalAlignment(Element.ALIGN_LEFT);
        PdfPCell pro1 = new PdfPCell(new Phrase("Producto:", negrita));
        PdfPCell pro2 = new PdfPCell(new Phrase("Tamaño:", negrita));
        PdfPCell pro3 = new PdfPCell(new Phrase("Cantidad:", negrita));
        PdfPCell pro4 = new PdfPCell(new Phrase("Precio:", negrita));
       
        pro1.setBorder(0);
        pro2.setBorder(0);
        pro3.setBorder(0);
        pro4.setBorder(0);
        pro1.setBackgroundColor(BaseColor.RED);
        pro2.setBackgroundColor(BaseColor.RED);
        pro3.setBackgroundColor(BaseColor.RED);
        pro4.setBackgroundColor(BaseColor.RED);
        tabproductos.addCell(pro1);
        tabproductos.addCell(pro2);
        tabproductos.addCell(pro3);
        tabproductos.addCell(pro4);
        for(int i =0; i<tabla_pro.getRowCount(); i++){
            String producto = tabla_pro.getValueAt(i, 1).toString();
            String tamano = tabla_pro.getValueAt(i, 2).toString();
            String cantidad = tabla_pro.getValueAt(i, 3).toString();
            String precio = tabla_pro.getValueAt(i, 4).toString();
            
            tabproductos.addCell(producto);
            tabproductos.addCell(tamano);
            tabproductos.addCell(cantidad);
            tabproductos.addCell(precio);
            
            
        }
        
        doc.add(tabproductos);
        
        Paragraph info = new Paragraph();
        info.add(Chunk.NEWLINE);
        info.add("\nTotal: $"+ lbl_total.getText());
        info.setAlignment(Element.ALIGN_RIGHT);
        doc.add(info);
        
        Paragraph firma = new Paragraph();
        firma.add(Chunk.NEWLINE);
        firma.add("\nFIRMA:\n\n\n\n");
        firma.add("--------------------------------");
        firma.setAlignment(Element.ALIGN_CENTER);
        doc.add(firma);
        
        
        doc.close();
        archivo.close();
        Desktop.getDesktop().open(file);
     }catch(Exception e){
         System.out.println(e);
     } 
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accept;
    private javax.swing.JButton btn_actualizarcli;
    private javax.swing.JButton btn_agregarb;
    private javax.swing.JButton btn_agregarp;
    private javax.swing.JButton btn_cancelarcli;
    private javax.swing.JButton btn_eliminarcli;
    private javax.swing.JButton btn_elitabla;
    private javax.swing.JButton btn_guardarcli;
    private javax.swing.JButton btn_nuevocli;
    private javax.swing.JButton btn_regventa;
    private javax.swing.JButton btn_seleccionarb;
    private javax.swing.JButton btn_seleccionarp;
    private javax.swing.JButton btn_tabpro;
    private javax.swing.JComboBox<productos> cbx_bebida;
    private javax.swing.JComboBox<productos> cbx_pizza;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_ide;
    private javax.swing.JLabel lbl_total;
    private static javax.swing.JTable tabla_cliente;
    private javax.swing.JTable tabla_ord;
    private javax.swing.JTable tabla_p;
    private javax.swing.JTable tabla_pro;
    private javax.swing.JTextField txt_apecli;
    private javax.swing.JTextField txt_apecliv;
    private javax.swing.JTextField txt_cantb;
    private javax.swing.JTextField txt_cantp;
    private javax.swing.JTextField txt_cedcliv;
    public javax.swing.JTextField txt_cedulacli;
    private javax.swing.JTextField txt_correocli;
    private javax.swing.JTextField txt_correocliv;
    private javax.swing.JTextField txt_dircli;
    private javax.swing.JTextField txt_dircliv;
    private javax.swing.JTextField txt_id_cliente;
    private javax.swing.JTextField txt_idcliv;
    private javax.swing.JTextField txt_idventa;
    private javax.swing.JTextField txt_nombrecli;
    private javax.swing.JTextField txt_nombrecliv;
    private javax.swing.JTextField txt_preciob;
    private javax.swing.JTextField txt_preciop;
    private javax.swing.JTextField txt_telcli;
    private javax.swing.JTextField txt_telcliv;
    // End of variables declaration//GEN-END:variables
}
