/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import clases.cls_clientes;
import clases.cls_empleados;
import clases.orden;
import clases.productos;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSi
 */
public class frm_administrador extends javax.swing.JFrame {

    public static orden o = new orden();
    public static productos p = new productos();
    public static cls_clientes c = new cls_clientes();
    public static cls_empleados e = new cls_empleados();
    public static DefaultTableModel modelord;
    public static DefaultTableModel modp;
    public static DefaultTableModel modb;
    public static DefaultTableModel modc;
    public static DefaultTableModel mode;
    /**
     * Creates new form frm_administrador
     */
    public frm_administrador() {
        initComponents();
        
        Icon logo1 = new ImageIcon(new ImageIcon(getClass().getResource("/imagenes/logo1.png")).getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), 0));
        jLabel2.setIcon(logo1);
        txt_idv.setVisible(false);
        txt_idprod.setVisible(false);
        txt_idbe.setVisible(false);
        txt_null.setVisible(false);
        txt_idcli.setVisible(false);
        txt_ide.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_orden = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_idv = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab_pizza = new javax.swing.JTable();
        txt_pizza = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbx_tamano = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_idprod = new javax.swing.JTextField();
        btn_nuevo = new javax.swing.JButton();
        btn_grdp = new javax.swing.JButton();
        btn_actualizap = new javax.swing.JButton();
        btn_eliminap = new javax.swing.JButton();
        btn_cancelap = new javax.swing.JButton();
        txt_null = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab_bebida = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txt_bebida = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_preciob = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btn_nuevob = new javax.swing.JButton();
        btn_guardarb = new javax.swing.JButton();
        btn_actualizab = new javax.swing.JButton();
        btn_eliminab = new javax.swing.JButton();
        btn_cancelab = new javax.swing.JButton();
        txt_idbe = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txt_idcli = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_cicli = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_nombrec = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_apellidoc = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_telc = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_dirc = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_correoc = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tab_cli = new javax.swing.JTable();
        btn_nuevoc = new javax.swing.JButton();
        btn_guardarc = new javax.swing.JButton();
        btn_actualizac = new javax.swing.JButton();
        btn_eliminac = new javax.swing.JButton();
        btn_cancelac = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txt_ide = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txt_cede = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txt_nombree = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_apellidoe = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txt_tele = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cbx_cargoe = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        txt_dire = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txt_correoe = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_passe = new javax.swing.JPasswordField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tab_em = new javax.swing.JTable();
        btn_nuevoe = new javax.swing.JButton();
        btn_guardare = new javax.swing.JButton();
        btn_actualizae = new javax.swing.JButton();
        btn_eliminae = new javax.swing.JButton();
        btn_cancelae = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1140, 560));
        setPreferredSize(new java.awt.Dimension(1140, 560));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Order Pizza", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/orden1.png"))); // NOI18N
        jButton1.setText("Ordenes");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Order Pizza", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoorden.png"))); // NOI18N
        jButton2.setText("Pizzas");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Order Pizza", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inconocliente.png"))); // NOI18N
        jButton3.setText("Clientes");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Order Pizza", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-personal-32.png"))); // NOI18N
        jButton4.setText("Personal");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Order Pizza", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-lata-de-refresco-32.png"))); // NOI18N
        jButton6.setText("Bebidas");
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 570));

        jLabel3.setFont(new java.awt.Font("Order Pizza", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Administrador");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banner4.jpg"))); // NOI18N
        jLabel1.setText("Mo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 890, 130));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_orden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "# ORDEN", "Nombre Cliente", "Apellido Cliente", "Cod. Cajero", "Total"
            }
        ));
        tab_orden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_ordenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_orden);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 640, 260));

        jLabel4.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel4.setText("Seleccione la fila que desea imprimir:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 27, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impreg.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 90, 80));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-derecha-abajo-2-32.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));
        jPanel1.add(txt_idv, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 20, -1));

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel5.setText("Especialidad:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 84, -1, -1));

        tab_pizza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Pizza", "Especialidad", "Tamaño", "Precio"
            }
        ));
        tab_pizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_pizzaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tab_pizza);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 500, 270));
        jPanel3.add(txt_pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 84, 116, -1));

        jLabel6.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel6.setText("Size:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 126, -1, -1));

        cbx_tamano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Individual", "Mediana", "Familiar", "XL" }));
        jPanel3.add(cbx_tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 126, 192, -1));

        jLabel7.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel7.setText("Precio:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 168, -1, -1));
        jPanel3.add(txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 168, 71, -1));

        jLabel8.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel8.setText("$");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 168, -1, -1));

        jLabel9.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel9.setText("Seleccione la pizza que desea actualizar o eliminar:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 23, 430, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-derecha-abajo-2-32.png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 43, -1));
        jPanel3.add(txt_idprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 20, -1));

        btn_nuevo.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btn_nuevo.setText("Nuevo");
        btn_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, -1));

        btn_grdp.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_grdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_grdp.setText("Guardar");
        btn_grdp.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_grdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grdpActionPerformed(evt);
            }
        });
        jPanel3.add(btn_grdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        btn_actualizap.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_actualizap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizap.setText("Actualizar");
        btn_actualizap.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_actualizap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizapActionPerformed(evt);
            }
        });
        jPanel3.add(btn_actualizap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 140, 40));

        btn_eliminap.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_eliminap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_eliminap.setText("Eliminar");
        btn_eliminap.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_eliminap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminapActionPerformed(evt);
            }
        });
        jPanel3.add(btn_eliminap, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 120, -1));

        btn_cancelap.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_cancelap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btn_cancelap.setText("Cancelar");
        btn_cancelap.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_cancelap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelapActionPerformed(evt);
            }
        });
        jPanel3.add(btn_cancelap, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 130, -1));
        jPanel3.add(txt_null, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 20, -1));

        jTabbedPane1.addTab("tab2", jPanel3);

        jLabel12.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel12.setText("Seleccionar la bebida que desea actualizar o eliminar:");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-derecha-abajo-2-32.png"))); // NOI18N

        tab_bebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Bebida", "Bebida", "Precio"
            }
        ));
        tab_bebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_bebidaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tab_bebida);

        jLabel14.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel14.setText("Bebida:");

        jLabel15.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel15.setText("Precio:");

        jLabel16.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel16.setText("$");

        btn_nuevob.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_nuevob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btn_nuevob.setText("Nuevo");
        btn_nuevob.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_nuevob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevobActionPerformed(evt);
            }
        });

        btn_guardarb.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_guardarb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardarb.setText("Guardar");
        btn_guardarb.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_guardarb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarbActionPerformed(evt);
            }
        });

        btn_actualizab.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_actualizab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizab.setText("Actualizar");
        btn_actualizab.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_actualizab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizabActionPerformed(evt);
            }
        });

        btn_eliminab.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_eliminab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_eliminab.setText("Eliminar");
        btn_eliminab.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_eliminab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminabActionPerformed(evt);
            }
        });

        btn_cancelab.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_cancelab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btn_cancelab.setText("Cancelar");
        btn_cancelab.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_cancelab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_preciob, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btn_nuevob, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_guardarb))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(btn_actualizab)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_eliminab))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(txt_idbe, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btn_cancelab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txt_idbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_bebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(txt_preciob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_nuevob)
                            .addComponent(btn_guardarb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_actualizab, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_eliminab))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancelab))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(txt_idcli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, -1));

        jLabel17.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel17.setText("CI o RUC:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));
        jPanel5.add(txt_cicli, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 150, -1));

        jLabel18.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel18.setText("Nombre:");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        jPanel5.add(txt_nombrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 150, -1));

        jLabel19.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel19.setText("Apellido:");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        jPanel5.add(txt_apellidoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 150, -1));

        jLabel20.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel20.setText("Telefono:");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jPanel5.add(txt_telc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, -1));

        jLabel21.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel21.setText("Direccion:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jPanel5.add(txt_dirc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 150, -1));

        jLabel22.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel22.setText("Correo:");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        jPanel5.add(txt_correoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 150, -1));

        jLabel23.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel23.setText("Seleccione el cliente que desea actualizar o eliminar:");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-derecha-abajo-2-32.png"))); // NOI18N
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        tab_cli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula o RUC", "Nombre", "Apellido", "Teléfono", "Dirección", "Correo"
            }
        ));
        tab_cli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_cliMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tab_cli);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 590, 170));

        btn_nuevoc.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        btn_nuevoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btn_nuevoc.setText("Nuevo");
        btn_nuevoc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_nuevoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevocActionPerformed(evt);
            }
        });
        jPanel5.add(btn_nuevoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        btn_guardarc.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        btn_guardarc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardarc.setText("Guardar");
        btn_guardarc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_guardarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarcActionPerformed(evt);
            }
        });
        jPanel5.add(btn_guardarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        btn_actualizac.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        btn_actualizac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizac.setText("Actualizar");
        btn_actualizac.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_actualizac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizacActionPerformed(evt);
            }
        });
        jPanel5.add(btn_actualizac, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, 40));

        btn_eliminac.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        btn_eliminac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_eliminac.setText("Eliminar");
        btn_eliminac.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_eliminac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminacActionPerformed(evt);
            }
        });
        jPanel5.add(btn_eliminac, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        btn_cancelac.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        btn_cancelac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btn_cancelac.setText("Cancelar");
        btn_cancelac.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_cancelac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelacActionPerformed(evt);
            }
        });
        jPanel5.add(btn_cancelac, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, -1, -1));

        jTabbedPane1.addTab("tab4", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(txt_ide, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, -1));

        jLabel25.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel25.setText("CI:");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
        jPanel6.add(txt_cede, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 140, -1));

        jLabel26.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel26.setText("Nombre:");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel6.add(txt_nombree, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 140, -1));

        jLabel27.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel27.setText("Apellido:");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel6.add(txt_apellidoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 140, -1));

        jLabel28.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel28.setText("Telefono:");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        jPanel6.add(txt_tele, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, -1));

        jLabel29.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel29.setText("Cargo:");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        cbx_cargoe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cajero", "Administrador" }));
        jPanel6.add(cbx_cargoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 140, -1));

        jLabel30.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel30.setText("Direccion:");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        jPanel6.add(txt_dire, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 140, -1));

        jLabel31.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel31.setText("Correo:");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel6.add(txt_correoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 140, -1));

        jLabel32.setFont(new java.awt.Font("Order Pizza", 0, 8)); // NOI18N
        jLabel32.setText("Clave:");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));
        jPanel6.add(txt_passe, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 140, -1));

        jLabel33.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        jLabel33.setText("Seleccione al empleado que desea actualizar o eliminar:");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-derecha-abajo-2-32.png"))); // NOI18N
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        tab_em.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Teléfono", "Cargo", "Dirección", "Correo"
            }
        ));
        tab_em.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_emMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tab_em);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 600, 210));

        btn_nuevoe.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        btn_nuevoe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btn_nuevoe.setText("Nuevo");
        btn_nuevoe.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_nuevoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoeActionPerformed(evt);
            }
        });
        jPanel6.add(btn_nuevoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        btn_guardare.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        btn_guardare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btn_guardare.setText("Guardar");
        btn_guardare.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_guardare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardareActionPerformed(evt);
            }
        });
        jPanel6.add(btn_guardare, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        btn_actualizae.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        btn_actualizae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        btn_actualizae.setText("Actualizar");
        btn_actualizae.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_actualizae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizaeActionPerformed(evt);
            }
        });
        jPanel6.add(btn_actualizae, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 40));

        btn_eliminae.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        btn_eliminae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btn_eliminae.setText("Eliminar");
        btn_eliminae.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_eliminae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminaeActionPerformed(evt);
            }
        });
        jPanel6.add(btn_eliminae, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        btn_cancelae.setFont(new java.awt.Font("Order Pizza", 0, 10)); // NOI18N
        btn_cancelae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        btn_cancelae.setText("Cancelar");
        btn_cancelae.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_cancelae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelaeActionPerformed(evt);
            }
        });
        jPanel6.add(btn_cancelae, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, -1, -1));

        jTabbedPane1.addTab("tab5", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 880, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        tablaO();
        
        
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        jTabbedPane1.setSelectedIndex(0);
        tablaO();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        int id = Integer.parseInt(txt_idv.getText());
        File file = new File("src/pdf/factura"+id+".pdf");
        try {
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(frm_administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tab_ordenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_ordenMouseClicked
        
        int fila = tab_orden.rowAtPoint(evt.getPoint());
        txt_idv.setText(tab_orden.getValueAt(fila, 0).toString());
        
    }//GEN-LAST:event_tab_ordenMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        jTabbedPane1.setSelectedIndex(1);
        bcajasp();
        bbotonp();
        try {
            tablaP();
        } catch (SQLException ex) {
            Logger.getLogger(frm_administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        btn_nuevo.setEnabled(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_grdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grdpActionPerformed
        
        p.setProducto(txt_pizza.getText());
        p.setTamano(cbx_tamano.getSelectedItem().toString());
        p.setPrecio(Double.parseDouble(txt_precio.getText()));
        
        try {
            if(p.insertarPizza()){
                bcajasp();
                lcajasp();
                bbotonp();
                btn_nuevo.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
                tablaP();
            }else{
                JOptionPane.showMessageDialog(null, "Error al guardar.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(frm_administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_grdpActionPerformed

    private void tab_pizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_pizzaMouseClicked
        
        int id = Integer.parseInt(tab_pizza.getValueAt(tab_pizza.getSelectedRow(), 0).toString());
        String [] dato = new String [4];
        dato = p.consultarProducto(id);
        
        if(dato != null){
            bbotonp();
            btn_eliminap.setEnabled(true);
            btn_actualizap.setEnabled(true);
            btn_cancelap.setEnabled(true);
            acajasp();
            txt_idprod.setText(dato[0]);
            txt_pizza.setText(dato[1]);
            cbx_tamano.setSelectedItem(dato[2]);
            txt_precio.setText(dato[3]);
        }
        
    }//GEN-LAST:event_tab_pizzaMouseClicked

    private void btn_actualizapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizapActionPerformed
        
        p.setProducto(txt_pizza.getText());
        p.setTamano(cbx_tamano.getSelectedItem().toString());
        p.setPrecio(Double.parseDouble(txt_precio.getText()));
        p.setId_producto(Integer.parseInt(txt_idprod.getText()));
        
        if(p.actualizarPizza()==true){
            JOptionPane.showMessageDialog(null, "Datos actualizados correctamente.");
            bcajasp();
            lcajasp();
            bbotonp();
            btn_nuevo.setEnabled(true);
            try {
                tablaP();
            } catch (SQLException ex) {
                Logger.getLogger(frm_administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error al actualizar los datos.");
        }
        
    }//GEN-LAST:event_btn_actualizapActionPerformed

    private void btn_eliminapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminapActionPerformed
        
        int respuesta = JOptionPane.showConfirmDialog(null, "Está seguro de eliminar el producto?");
        if(respuesta==0){
            p.setId_producto(Integer.parseInt(txt_idprod.getText()));
            if(p.eliminarProducto()){
                JOptionPane.showMessageDialog(null, "Producto eliminado.");
                bcajasp();
                lcajasp();
                bbotonp();
                btn_nuevo.setEnabled(true);
                try {
                    tablaP();
                } catch (SQLException ex) {
                    Logger.getLogger(frm_administrador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar el producto.");
            }
        }
        
    }//GEN-LAST:event_btn_eliminapActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        
        acajasp();
        btn_grdp.setEnabled(true);
        btn_cancelap.setEnabled(true);
        
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_cancelapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelapActionPerformed
        
        bcajasp();
        lcajasp();
        bbotonp();
        btn_nuevo.setEnabled(true);
        
    }//GEN-LAST:event_btn_cancelapActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        jTabbedPane1.setSelectedIndex(2);
        bcajasb();
        bbotonb();
        try {
            tablaB();
        } catch (SQLException ex) {
            Logger.getLogger(frm_administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        btn_nuevob.setEnabled(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tab_bebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_bebidaMouseClicked
       
        int idb = Integer.parseInt(tab_bebida.getValueAt(tab_bebida.getSelectedRow(), 0).toString());
        txt_idbe.setText(tab_bebida.getValueAt(tab_bebida.getSelectedRow(), 0).toString());
        String [] dato = new String [2];
        dato = p.consultarBebida(idb);
        
        if(dato != null){
            bbotonb();
            btn_eliminab.setEnabled(true);
            btn_actualizab.setEnabled(true);
            btn_cancelab.setEnabled(true);
            acajasb();
            txt_bebida.setText(dato[0]);
            txt_preciob.setText(dato[1]);
        }
        
        
    }//GEN-LAST:event_tab_bebidaMouseClicked

    private void btn_nuevobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevobActionPerformed
        
        acajasb();
        btn_guardarb.setEnabled(true);
        btn_cancelab.setEnabled(true);
        
    }//GEN-LAST:event_btn_nuevobActionPerformed

    private void btn_guardarbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarbActionPerformed
        
        
        p.setProducto(txt_bebida.getText());
        p.setPrecio(Double.parseDouble(txt_preciob.getText()));
        
        if(p.insertarBebida()==true){
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
            bcajasb();
            lcajasb();
            bbotonb();
            btn_nuevob.setEnabled(true);
            try {
                tablaB();
            } catch (SQLException ex) {
                Logger.getLogger(frm_administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error al guardar.");
        }
        
    }//GEN-LAST:event_btn_guardarbActionPerformed

    private void btn_cancelabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelabActionPerformed
        
        bcajasb();
        lcajasb();
        bbotonb();
        btn_nuevob.setEnabled(true);
        
    }//GEN-LAST:event_btn_cancelabActionPerformed

    private void btn_actualizabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizabActionPerformed
        
        p.setProducto(txt_bebida.getText());
        p.setPrecio(Double.parseDouble(txt_preciob.getText()));
        p.setId_producto(Integer.parseInt(txt_idbe.getText()));
        
        if(p.actualizarBebida()==true){
            
            JOptionPane.showMessageDialog(null, "Bebida actualizada correctamente.");
            bcajasb();
            lcajasb();
            bbotonb();
            btn_nuevob.setEnabled(true);
            try {
                tablaB();
            } catch (SQLException ex) {
                Logger.getLogger(frm_administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error al actualizar bebida.");
        }
        
    }//GEN-LAST:event_btn_actualizabActionPerformed

    private void btn_eliminabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminabActionPerformed
        
        int respuesta = JOptionPane.showConfirmDialog(null, "Seguro de eliminar la bebida?");
        if(respuesta==0){
            p.setId_producto(Integer.parseInt(txt_idbe.getText()));
            if(p.eliminarProducto()){
                JOptionPane.showMessageDialog(null, "Bebida eliminada.");
                bcajasb();
                lcajasb();
                bbotonb();
                btn_nuevob.setEnabled(true);
                try {
                    tablaB();
                } catch (SQLException ex) {
                    Logger.getLogger(frm_administrador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar la bebida.");
            }
        }
        
    }//GEN-LAST:event_btn_eliminabActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        jTabbedPane1.setSelectedIndex(3);
        bcajasc();
        bbotonc();
        btn_nuevoc.setEnabled(true);
        tablaC();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tab_cliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_cliMouseClicked
        
        String cedula = tab_cli.getValueAt(tab_cli.getSelectedRow(), 0).toString();
        String [] dato = new String [7];
        dato = c.consultarCed(cedula);
        
        if(dato != null){
            
            bbotonc();
            btn_eliminac.setEnabled(true);
            btn_actualizac.setEnabled(true);
            btn_cancelac.setEnabled(true);
            acajasc();
            txt_idcli.setText(dato[0]);
            txt_cicli.setText(dato[1]);
            txt_nombrec.setText(dato[2]);
            txt_apellidoc.setText(dato[3]);
            txt_telc.setText(dato[4]);
            txt_dirc.setText(dato[5]);
            txt_correoc.setText(dato[6]);
        }
        
    }//GEN-LAST:event_tab_cliMouseClicked

    private void btn_nuevocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevocActionPerformed
        
        acajasc();
        btn_guardarc.setEnabled(true);
        btn_cancelac.setEnabled(true);
        
    }//GEN-LAST:event_btn_nuevocActionPerformed

    private void btn_guardarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarcActionPerformed
        
        c.setCedula(txt_cicli.getText());
        c.setNombre(txt_nombrec.getText());
        c.setApellido(txt_apellidoc.getText());
        c.setTelefono(txt_telc.getText());
        c.setDireccion(txt_dirc.getText());
        c.setCorreo(txt_correoc.getText());
        
        if(c.insertar()==true){
            
            JOptionPane.showMessageDialog(null, "Cliente guardado correctamente.");
            bcajasc();
            lcajasc();
            bbotonc();
            btn_nuevoc.setEnabled(true);
            tablaC();
        }else{
            JOptionPane.showMessageDialog(null, "Error al guardar al cliente.");
        }
        
    }//GEN-LAST:event_btn_guardarcActionPerformed

    private void btn_actualizacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizacActionPerformed
        
        c.setCedula(txt_cicli.getText());
        c.setNombre(txt_nombrec.getText());
        c.setApellido(txt_apellidoc.getText());
        c.setTelefono(txt_telc.getText());
        c.setDireccion(txt_dirc.getText());
        c.setCorreo(txt_correoc.getText());
        c.setId_cliente(Integer.parseInt(txt_idcli.getText()));
        
        if(c.actualizar()){
            
            JOptionPane.showMessageDialog(null, "Cliente actualizado correctamente.");
            bcajasc();
            lcajasc();
            bbotonc();
            btn_nuevoc.setEnabled(true);
            tablaC();
        }else{
            JOptionPane.showMessageDialog(null, "Error al actualizar al cliente");
        }
        
    }//GEN-LAST:event_btn_actualizacActionPerformed

    private void btn_eliminacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminacActionPerformed
        
        int respuesta = JOptionPane.showConfirmDialog(null, "Está seguro de eliminar al cliente?");
        if(respuesta==0){
            c.setId_cliente(Integer.parseInt(txt_idcli.getText()));
            if(c.eliminar()){
                JOptionPane.showMessageDialog(null, "Cliente eliminado correctamente.");
                bcajasc();
                lcajasc();
                bbotonc();
                btn_nuevoc.setEnabled(true);
                tablaC();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar al cliente");
            }
        }
        
    }//GEN-LAST:event_btn_eliminacActionPerformed

    private void btn_cancelacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelacActionPerformed
        
        bcajasc();
        lcajasc();
        bbotonc();
        btn_nuevoc.setEnabled(true);
        
    }//GEN-LAST:event_btn_cancelacActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        jTabbedPane1.setSelectedIndex(4);
        tablaE();
        bcajase();
        bbotone();
        btn_nuevoe.setEnabled(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tab_emMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_emMouseClicked
        
        String cedula = tab_em.getValueAt(tab_em.getSelectedRow(), 0).toString();
        String [] dato = new String [9];
        try {
            dato = e.consultarE(cedula);
        } catch (SQLException ex) {
            Logger.getLogger(frm_administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(dato != null){
            bbotone();
            btn_eliminae.setEnabled(true);
            btn_actualizae.setEnabled(true);
            btn_cancelae.setEnabled(true);
            acajase();
            txt_ide.setText(dato[0]);
            txt_cede.setText(dato[1]);
            txt_nombree.setText(dato[2]);
            txt_apellidoe.setText(dato[3]);
            txt_tele.setText(dato[4]);
            cbx_cargoe.setSelectedItem(dato[5]);
            txt_dire.setText(dato[6]);
            txt_correoe.setText(dato[7]);
            txt_passe.setText(dato[8]);
        }
        
    }//GEN-LAST:event_tab_emMouseClicked

    private void btn_nuevoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoeActionPerformed
        
        acajase();
        btn_guardare.setEnabled(true);
        btn_cancelae.setEnabled(true);
        
    }//GEN-LAST:event_btn_nuevoeActionPerformed

    private void btn_guardareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardareActionPerformed
        
        e.setCedula(txt_cede.getText());
        e.setNombre(txt_nombree.getText());
        e.setApellido(txt_apellidoe.getText());
        e.setTelefono(txt_tele.getText());
        e.setCargo(cbx_cargoe.getSelectedItem().toString());
        e.setDireccion(txt_dire.getText());
        e.setCorreo(txt_correoe.getText());
        e.setClave(txt_passe.getText());
        
        if(e.insertar()){
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
            bcajase();
            lcajase();
            bbotone();
            btn_nuevoe.setEnabled(true);
            tablaE();
        }else{
            JOptionPane.showMessageDialog(null, "Error al guardar los datos.");
        }
        
    }//GEN-LAST:event_btn_guardareActionPerformed

    private void btn_actualizaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizaeActionPerformed
        
        e.setCedula(txt_cede.getText());
        e.setNombre(txt_nombree.getText());
        e.setApellido(txt_apellidoe.getText());
        e.setTelefono(txt_tele.getText());
        e.setCargo(cbx_cargoe.getSelectedItem().toString());
        e.setDireccion(txt_dire.getText());
        e.setCorreo(txt_correoe.getText());
        e.setClave(txt_passe.getText());
        
        if(e.actualizar()){
            JOptionPane.showMessageDialog(null, "Datos actualizados.");
            bcajase();
            lcajase();
            bbotone();
            btn_nuevoe.setEnabled(true);
            tablaE();
        }else{
            JOptionPane.showMessageDialog(null, "Error al actualizar los datos.");
        }
        
    }//GEN-LAST:event_btn_actualizaeActionPerformed

    private void btn_eliminaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminaeActionPerformed
        
        int respuesta = JOptionPane.showConfirmDialog(null, "Está seguro de eliminar el registro?");
        if(respuesta == 0){
            e.setId_empleado(Integer.parseInt(txt_ide.getText()));
            try {
                if(e.eliminar()){
                    JOptionPane.showMessageDialog(null, "Registro eliminado.");
                    bcajase();
                    lcajase();
                    bbotone();
                    btn_nuevoe.setEnabled(true);
                    tablaE();
                }else{
                    JOptionPane.showMessageDialog(null, "Error al eliminar el registro.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(frm_administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btn_eliminaeActionPerformed

    private void btn_cancelaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelaeActionPerformed
        
        bcajase();
        lcajase();
        bbotone();
        btn_nuevoe.setEnabled(true);
        
    }//GEN-LAST:event_btn_cancelaeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_administrador().setVisible(true);
            }
        });
    }
    
    public void tablaO(){
        
        String [] cabecera = {"# ORDEN", "Nombre Cliente", "Apellido Cliente", "Cod. Cajero", "Total"};
        modelord = new DefaultTableModel(o.consultarOrden(), cabecera);
        tab_orden.setModel(modelord);
        
    }
    
    public void tablaE(){
        
        String [] cabecera = {"Cédula", "Nombre", "Apellido", "Teléfono", "Cargo", "Dirección", "Correo"};
        mode = new DefaultTableModel(e.consultar(), cabecera);
        tab_em.setModel(mode);
        
    }
    
    public void tablaC(){
        
        String [] cabecera = {"Cédula", "Nombre", "Apellido", "Teléfono", "Dirección", "Correo"};
        modc= new DefaultTableModel(c.consultar(txt_cicli.getText()), cabecera);
        tab_cli.setModel(modc);
        
    }
    
    public void tablaP() throws SQLException{
        
        String [] cabecera = {"Cod. Pizza", "Especialidad", "Tamaño", "Precio"};
        modp = new DefaultTableModel(p.consultarP(), cabecera);
        tab_pizza.setModel(modp);
        
    }
    
    public void tablaB() throws SQLException{
        
        String [] cabecera = {"Cod. Bebida", "Bebida + tamaño","", "Precio"};
        modb = new DefaultTableModel(p.consultarB(), cabecera);
        tab_bebida.setModel(modb);
    }
    
    public void bcajase(){
        
        this.txt_cede.setEnabled(false);
        this.txt_nombree.setEnabled(false);
        this.txt_apellidoe.setEnabled(false);
        this.txt_tele.setEnabled(false);
        this.txt_dire.setEnabled(false);
        this.txt_correoe.setEnabled(false);
        this.txt_passe.setEnabled(false);
    }
    
    public void acajase(){
        
        this.txt_cede.setEnabled(true);
        this.txt_nombree.setEnabled(true);
        this.txt_apellidoe.setEnabled(true);
        this.txt_tele.setEnabled(true);
        this.txt_dire.setEnabled(true);
        this.txt_correoe.setEnabled(true);
        this.txt_passe.setEnabled(true);
    }
    
    public void lcajase(){
        
        this.txt_cede.setText("");
        this.txt_nombree.setText("");
        this.txt_apellidoe.setText("");
        this.txt_tele.setText("");
        this.txt_dire.setText("");
        this.txt_correoe.setText("");
        this.txt_passe.setText("");
    }
    
    public void bbotone(){
        
        this.btn_nuevoe.setEnabled(false);
        this.btn_guardare.setEnabled(false);
        this.btn_actualizae.setEnabled(false);
        this.btn_eliminae.setEnabled(false);
        this.btn_cancelae.setEnabled(false);
    }
    
    public void bcajasp(){
        this.txt_pizza.setEnabled(false);
        this.cbx_tamano.setEnabled(false);
        this.txt_precio.setEnabled(false);
    }
    
    public void bcajasc(){
        
        this.txt_cicli.setEnabled(false);
        this.txt_nombrec.setEnabled(false);
        this.txt_apellidoc.setEnabled(false);
        this.txt_telc.setEnabled(false);
        this.txt_dirc.setEnabled(false);
        this.txt_correoc.setEnabled(false);
    }
    
     public void acajasc(){
        
        this.txt_cicli.setEnabled(true);
        this.txt_nombrec.setEnabled(true);
        this.txt_apellidoc.setEnabled(true);
        this.txt_telc.setEnabled(true);
        this.txt_dirc.setEnabled(true);
        this.txt_correoc.setEnabled(true);
    }
     
    public void lcajasc(){
        
        this.txt_cicli.setText("");
        this.txt_nombrec.setText("");
        this.txt_apellidoc.setText("");
        this.txt_telc.setText("");
        this.txt_dirc.setText("");
        this.txt_correoc.setText("");
        
    }
    
    public void bbotonc(){
        
        this.btn_nuevoc.setEnabled(false);
        this.btn_guardarc.setEnabled(false);
        this.btn_actualizac.setEnabled(false);
        this.btn_eliminac.setEnabled(false);
        this.btn_cancelac.setEnabled(false);
    }
    
    public void bcajasb(){
        
        this.txt_bebida.setEnabled(false);
        this.txt_preciob.setEnabled(false);
        
    }
    
    public void acajasb(){
        
        this.txt_bebida.setEnabled(true);
        this.txt_preciob.setEnabled(true);
        
    }
    
    public void lcajasb(){
        
        this.txt_bebida.setText("");
        this.txt_preciob.setText("");
        
    }
    
    public void bbotonb(){
        
        this.btn_nuevob.setEnabled(false);
        this.btn_guardarb.setEnabled(false);
        this.btn_actualizab.setEnabled(false);
        this.btn_eliminab.setEnabled(false);
        this.btn_cancelab.setEnabled(false);
    }
    
    public void acajasp(){
        this.txt_pizza.setEnabled(true);
        this.cbx_tamano.setEnabled(true);
        this.txt_precio.setEnabled(true);
    }
    
    public void lcajasp(){
        this.txt_pizza.setText("");
        this.txt_precio.setText("");
    }
    
    public void bbotonp(){
        this.btn_nuevo.setEnabled(false);
        this.btn_grdp.setEnabled(false);
        this.btn_cancelap.setEnabled(false);
        this.btn_eliminap.setEnabled(false);
        this.btn_actualizap.setEnabled(false);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizab;
    private javax.swing.JButton btn_actualizac;
    private javax.swing.JButton btn_actualizae;
    private javax.swing.JButton btn_actualizap;
    private javax.swing.JButton btn_cancelab;
    private javax.swing.JButton btn_cancelac;
    private javax.swing.JButton btn_cancelae;
    private javax.swing.JButton btn_cancelap;
    private javax.swing.JButton btn_eliminab;
    private javax.swing.JButton btn_eliminac;
    private javax.swing.JButton btn_eliminae;
    private javax.swing.JButton btn_eliminap;
    private javax.swing.JButton btn_grdp;
    private javax.swing.JButton btn_guardarb;
    private javax.swing.JButton btn_guardarc;
    private javax.swing.JButton btn_guardare;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_nuevob;
    private javax.swing.JButton btn_nuevoc;
    private javax.swing.JButton btn_nuevoe;
    private javax.swing.JComboBox<String> cbx_cargoe;
    private javax.swing.JComboBox<String> cbx_tamano;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tab_bebida;
    private javax.swing.JTable tab_cli;
    private javax.swing.JTable tab_em;
    private javax.swing.JTable tab_orden;
    private javax.swing.JTable tab_pizza;
    private javax.swing.JTextField txt_apellidoc;
    private javax.swing.JTextField txt_apellidoe;
    private javax.swing.JTextField txt_bebida;
    private javax.swing.JTextField txt_cede;
    private javax.swing.JTextField txt_cicli;
    private javax.swing.JTextField txt_correoc;
    private javax.swing.JTextField txt_correoe;
    private javax.swing.JTextField txt_dirc;
    private javax.swing.JTextField txt_dire;
    private javax.swing.JTextField txt_idbe;
    private javax.swing.JTextField txt_idcli;
    private javax.swing.JTextField txt_ide;
    private javax.swing.JTextField txt_idprod;
    private javax.swing.JTextField txt_idv;
    private javax.swing.JTextField txt_nombrec;
    private javax.swing.JTextField txt_nombree;
    private javax.swing.JTextField txt_null;
    private javax.swing.JPasswordField txt_passe;
    private javax.swing.JTextField txt_pizza;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_preciob;
    private javax.swing.JTextField txt_telc;
    private javax.swing.JTextField txt_tele;
    // End of variables declaration//GEN-END:variables
}
